module.exports = {
  HEADERS: {
    FOCUS_GROUP: 'FGD',
    PERCENTAGE: 'Percentage',
    GROUP: 'Group',
    LEG_1: 'Leg_1',
    LEG_2: 'Leg_2',
    LEG_3: 'Leg_3',
    LEG_4: 'Leg_4',
    LEG_5: 'Leg_5',
  },
  ROUTES: [
    {
      FOCUS_GROUP: 'FGD',
      PERCENTAGE: 'R1%',
      GROUP: 'R1_Group',
      LEG_1: 'R1_L1',
      LEG_2: 'R1_L2',
      LEG_3: 'R1_L3',
      LEG_4: 'R1_L4',
      LEG_5: '',
    },
    {
      FOCUS_GROUP: 'FGD',
      PERCENTAGE: 'R2%',
      GROUP: 'R2_Group',
      LEG_1: 'R2_L1',
      LEG_2: 'R2_L2',
      LEG_3: 'R2_L3',
      LEG_4: 'R2_L4',
      LEG_5: '',
    },
    {
      FOCUS_GROUP: 'FGD',
      PERCENTAGE: 'R3%',
      GROUP: 'R3_Group',
      LEG_1: 'R3_L1',
      LEG_2: 'R3_L2',
      LEG_3: 'R3_L3',
      LEG_4: 'R3_L4',
      LEG_5: 'R3_L5',
    },
  ],
  ROUTES_SEPARATE_FILES: [
    {
      LEG_1: 'R1_L1',
      LEG_2: 'R1_L2',
      LEG_3: 'R1_L3',
      LEG_4: 'R1_L4',
      LEG_5: '',
    },
    {
      LEG_1: 'R2_L1',
      LEG_2: 'R2_L2',
      LEG_3: 'R2_L3',
      LEG_4: 'R2_L4',
      LEG_5: '',
    },
    {
      LEG_1: 'R3_L1',
      LEG_2: 'R3_L2',
      LEG_3: 'R3_L3',
      LEG_4: 'R3_L4',
      LEG_5: 'R3_L5',
    },
  ],
};
